version: '3.3'

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    environment:
      NGINX_HOST: ${NGINX_HOST}
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
  fpm:
    build:
      context: ${PWD}/docker/fpm
      args:
        COMPOSER_VERSION: 1.9.1
    volumes:
      - ./:/var/www
    working_dir: /var/www/src
    environment:
      - "XDEBUG_CONFIG=${XDEBUG_CONFIG}"
      - "COMPOSER_MEMORY_LIMIT=-1"
      - "PHP_IDE_CONFIG=${PHP_IDE_CONFIG}"
  db:
    image: percona:8
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/my.cnf:/etc/my.cnf
      - ./docker/db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}